language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
before_install:
  - composer selfupdate
install:
  - composer install --no-interaction --prefer-source
script:
  - ./bin/phpunit
notifications:
  email: false
